ALTER TABLE "discovered_content"
  ADD COLUMN IF NOT EXISTS "category" TEXT,
  ADD COLUMN IF NOT EXISTS "summary" TEXT,
  ADD COLUMN IF NOT EXISTS "metadata" JSONB,
  ADD COLUMN IF NOT EXISTS "quality_score" DOUBLE PRECISION DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "is_controversy" BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "is_history" BOOLEAN DEFAULT FALSE;
