[variables]
NIXPACKS_BUILD_CMD = "pip install -r requirements.txt"
NIXPACKS_START_CMD = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
