services:
  - type: web
    name: carrot-worker
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        value: redis://default:HktqFipUyOSWwBpjDzKRGmaOxUEvJYFx@redis.railway.internal:6379
      - key: INGEST_WORKER_SECRET
        value: dev_ingest_secret
      - key: PORT
        value: 10000
