services:
  - type: web
    name: carrot-worker
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        value: redis://default:HktqFipUyOSWwBpjDzKRGmaOxUEvJYFx@redis.railway.internal:6379
      - key: INGEST_WORKER_SECRET
        value: dev_ingest_secret
      - key: PORT
        value: 10000
      - key: YT_DLP_PATH
        value: yt-dlp
      - key: YT_DLP_COOKIES_FILE
        value: /app/cookies.txt
      - key: INGEST_CALLBACK_URL
        value: https://carrot-app.onrender.com/api/ingest/callback
      - key: INGEST_CALLBACK_SECRET
        value: dev_ingest_secret
      - key: WORKER_PUBLIC_URL
        value: https://carrot-worker.onrender.com
