services:
  - type: web
    name: carrot-worker
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    # Add health check and deployment settings
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        value: redis://default:HktqFipUyOSWwBpjDzKRGmaOxUEvJYFx@redis.railway.internal:6379
      - key: INGEST_WORKER_SECRET
        value: dev_ingest_secret
      - key: PORT
        value: 10000
      - key: YT_DLP_PATH
        value: yt-dlp
      - key: YT_DLP_COOKIES_FROM_BROWSER
        value: chrome
      - key: YT_DLP_COOKIES_FROM_BROWSER_PROFILE
        value: Default
      - key: INGEST_CALLBACK_URL
        value: https://carrot-app.onrender.com/api/ingest/callback
      - key: INGEST_CALLBACK_SECRET
        value: dev_ingest_secret
      - key: WORKER_PUBLIC_URL
        value: https://carrot-worker.onrender.com
      # Add HTTP/2 optimization settings
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048 --http-parser=legacy"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
