version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    volumes: 
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  router:
    build: ./router
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - VLLM_URL=http://vllm:8000
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      ollama:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # PostgreSQL for RAG (Phase 1+)
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=deepseek_rag
      - POSTGRES_USER=deepseek
      - POSTGRES_PASSWORD=deepseek_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  ollama_data:
  redis_data:
  postgres_data:
