name: build-and-push-worker

on:
  push:
    branches: [ main ]
    paths: [ "src/**", "package.json", "Dockerfile" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build+Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            danielgouldman1/carrot-worker:${{ github.sha }}
            danielgouldman1/carrot-worker:latest
