name: CI Ping

on:
  workflow_dispatch:
  push:
    branches: [ main, typescript-fixes-checkpoint-2025-08-14 ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: echo "GitHub Actions is enabled and indexing workflows."
