name: Deploy GCS CORS

on:
  workflow_dispatch:

env:
  BUCKET: involuted-river-466315-p0.appspot.com
  CORS_FILE: firebase-cors.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Apply CORS
        run: |
          echo "Applying CORS from '${{ env.CORS_FILE }}' to 'gs://${{ env.BUCKET }}'"
          gsutil cors set "${{ env.CORS_FILE }}" gs://${{ env.BUCKET }}

      - name: Verify CORS
        run: |
          gsutil cors get gs://${{ env.BUCKET }}
